export type KanaEntry = {
  id: string;
  script: "hiragana" | "katakana";
  char: string;
  romaji: string;
  confusion?: string[];
};

// Base gojūon with a few common confusions to build better distractors.
export const hiragana: KanaEntry[] = [
  { id: "a", script: "hiragana", char: "あ", romaji: "a" },
  { id: "i", script: "hiragana", char: "い", romaji: "i" },
  { id: "u", script: "hiragana", char: "う", romaji: "u" },
  { id: "e", script: "hiragana", char: "え", romaji: "e" },
  { id: "o", script: "hiragana", char: "お", romaji: "o" },
  { id: "ka", script: "hiragana", char: "か", romaji: "ka" },
  { id: "ki", script: "hiragana", char: "き", romaji: "ki" },
  { id: "ku", script: "hiragana", char: "く", romaji: "ku" },
  { id: "ke", script: "hiragana", char: "け", romaji: "ke" },
  { id: "ko", script: "hiragana", char: "こ", romaji: "ko" },
  { id: "sa", script: "hiragana", char: "さ", romaji: "sa" },
  { id: "shi", script: "hiragana", char: "し", romaji: "shi", confusion: ["tsu"] },
  { id: "su", script: "hiragana", char: "す", romaji: "su" },
  { id: "se", script: "hiragana", char: "せ", romaji: "se" },
  { id: "so", script: "hiragana", char: "そ", romaji: "so" },
  { id: "ta", script: "hiragana", char: "た", romaji: "ta" },
  { id: "chi", script: "hiragana", char: "ち", romaji: "chi", confusion: ["shi"] },
  { id: "tsu", script: "hiragana", char: "つ", romaji: "tsu", confusion: ["shi"] },
  { id: "te", script: "hiragana", char: "て", romaji: "te" },
  { id: "to", script: "hiragana", char: "と", romaji: "to" },
  { id: "na", script: "hiragana", char: "な", romaji: "na" },
  { id: "ni", script: "hiragana", char: "に", romaji: "ni" },
  { id: "nu", script: "hiragana", char: "ぬ", romaji: "nu", confusion: ["ne", "me"] },
  { id: "ne", script: "hiragana", char: "ね", romaji: "ne", confusion: ["nu", "me"] },
  { id: "no", script: "hiragana", char: "の", romaji: "no" },
  { id: "ha", script: "hiragana", char: "は", romaji: "ha" },
  { id: "hi", script: "hiragana", char: "ひ", romaji: "hi" },
  { id: "fu", script: "hiragana", char: "ふ", romaji: "fu" },
  { id: "he", script: "hiragana", char: "へ", romaji: "he" },
  { id: "ho", script: "hiragana", char: "ほ", romaji: "ho" },
  { id: "ma", script: "hiragana", char: "ま", romaji: "ma" },
  { id: "mi", script: "hiragana", char: "み", romaji: "mi" },
  { id: "mu", script: "hiragana", char: "む", romaji: "mu" },
  { id: "me", script: "hiragana", char: "め", romaji: "me", confusion: ["ne", "nu"] },
  { id: "mo", script: "hiragana", char: "も", romaji: "mo" },
  { id: "ya", script: "hiragana", char: "や", romaji: "ya" },
  { id: "yu", script: "hiragana", char: "ゆ", romaji: "yu" },
  { id: "yo", script: "hiragana", char: "よ", romaji: "yo" },
  { id: "ra", script: "hiragana", char: "ら", romaji: "ra" },
  { id: "ri", script: "hiragana", char: "り", romaji: "ri" },
  { id: "ru", script: "hiragana", char: "る", romaji: "ru" },
  { id: "re", script: "hiragana", char: "れ", romaji: "re" },
  { id: "ro", script: "hiragana", char: "ろ", romaji: "ro" },
  { id: "wa", script: "hiragana", char: "わ", romaji: "wa" },
  { id: "wo", script: "hiragana", char: "を", romaji: "o" },
  { id: "n", script: "hiragana", char: "ん", romaji: "n" },
];

export const katakana: KanaEntry[] = [
  { id: "a-k", script: "katakana", char: "ア", romaji: "a" },
  { id: "i-k", script: "katakana", char: "イ", romaji: "i" },
  { id: "u-k", script: "katakana", char: "ウ", romaji: "u" },
  { id: "e-k", script: "katakana", char: "エ", romaji: "e" },
  { id: "o-k", script: "katakana", char: "オ", romaji: "o" },
  { id: "ka-k", script: "katakana", char: "カ", romaji: "ka" },
  { id: "ki-k", script: "katakana", char: "キ", romaji: "ki" },
  { id: "ku-k", script: "katakana", char: "ク", romaji: "ku" },
  { id: "ke-k", script: "katakana", char: "ケ", romaji: "ke" },
  { id: "ko-k", script: "katakana", char: "コ", romaji: "ko" },
  { id: "sa-k", script: "katakana", char: "サ", romaji: "sa" },
  { id: "shi-k", script: "katakana", char: "シ", romaji: "shi", confusion: ["tsu-k"] },
  { id: "su-k", script: "katakana", char: "ス", romaji: "su" },
  { id: "se-k", script: "katakana", char: "セ", romaji: "se" },
  { id: "so-k", script: "katakana", char: "ソ", romaji: "so", confusion: ["n-k"] },
  { id: "ta-k", script: "katakana", char: "タ", romaji: "ta" },
  { id: "chi-k", script: "katakana", char: "チ", romaji: "chi", confusion: ["shi-k"] },
  { id: "tsu-k", script: "katakana", char: "ツ", romaji: "tsu", confusion: ["shi-k"] },
  { id: "te-k", script: "katakana", char: "テ", romaji: "te" },
  { id: "to-k", script: "katakana", char: "ト", romaji: "to" },
  { id: "na-k", script: "katakana", char: "ナ", romaji: "na" },
  { id: "ni-k", script: "katakana", char: "ニ", romaji: "ni" },
  { id: "nu-k", script: "katakana", char: "ヌ", romaji: "nu", confusion: ["ne-k", "me-k"] },
  { id: "ne-k", script: "katakana", char: "ネ", romaji: "ne", confusion: ["nu-k", "me-k"] },
  { id: "no-k", script: "katakana", char: "ノ", romaji: "no" },
  { id: "ha-k", script: "katakana", char: "ハ", romaji: "ha" },
  { id: "hi-k", script: "katakana", char: "ヒ", romaji: "hi" },
  { id: "fu-k", script: "katakana", char: "フ", romaji: "fu" },
  { id: "he-k", script: "katakana", char: "ヘ", romaji: "he" },
  { id: "ho-k", script: "katakana", char: "ホ", romaji: "ho" },
  { id: "ma-k", script: "katakana", char: "マ", romaji: "ma" },
  { id: "mi-k", script: "katakana", char: "ミ", romaji: "mi" },
  { id: "mu-k", script: "katakana", char: "ム", romaji: "mu" },
  { id: "me-k", script: "katakana", char: "メ", romaji: "me", confusion: ["ne-k", "nu-k"] },
  { id: "mo-k", script: "katakana", char: "モ", romaji: "mo" },
  { id: "ya-k", script: "katakana", char: "ヤ", romaji: "ya" },
  { id: "yu-k", script: "katakana", char: "ユ", romaji: "yu" },
  { id: "yo-k", script: "katakana", char: "ヨ", romaji: "yo" },
  { id: "ra-k", script: "katakana", char: "ラ", romaji: "ra" },
  { id: "ri-k", script: "katakana", char: "リ", romaji: "ri" },
  { id: "ru-k", script: "katakana", char: "ル", romaji: "ru" },
  { id: "re-k", script: "katakana", char: "レ", romaji: "re" },
  { id: "ro-k", script: "katakana", char: "ロ", romaji: "ro" },
  { id: "wa-k", script: "katakana", char: "ワ", romaji: "wa" },
  { id: "wo-k", script: "katakana", char: "ヲ", romaji: "o" },
  { id: "n-k", script: "katakana", char: "ン", romaji: "n", confusion: ["so-k"] },
];
