export type KanaEntry = {
  id: string;
  script: "hiragana" | "katakana";
  char: string;
  romaji: string;
  confusion?: string[];
};

// Complete gojūon (46 base characters) with common confusions
export const hiragana: KanaEntry[] = [
  { id: "a", script: "hiragana", char: "あ", romaji: "a" },
  { id: "i", script: "hiragana", char: "い", romaji: "i" },
  { id: "u", script: "hiragana", char: "う", romaji: "u" },
  { id: "e", script: "hiragana", char: "え", romaji: "e" },
  { id: "o", script: "hiragana", char: "お", romaji: "o" },
  { id: "ka", script: "hiragana", char: "か", romaji: "ka" },
  { id: "ki", script: "hiragana", char: "き", romaji: "ki" },
  { id: "ku", script: "hiragana", char: "く", romaji: "ku" },
  { id: "ke", script: "hiragana", char: "け", romaji: "ke" },
  { id: "ko", script: "hiragana", char: "こ", romaji: "ko" },
  { id: "ga", script: "hiragana", char: "が", romaji: "ga" },
  { id: "gi", script: "hiragana", char: "ぎ", romaji: "gi" },
  { id: "gu", script: "hiragana", char: "ぐ", romaji: "gu" },
  { id: "ge", script: "hiragana", char: "げ", romaji: "ge" },
  { id: "go", script: "hiragana", char: "ご", romaji: "go" },
  { id: "sa", script: "hiragana", char: "さ", romaji: "sa" },
  { id: "shi", script: "hiragana", char: "し", romaji: "shi", confusion: ["tsu"] },
  { id: "su", script: "hiragana", char: "す", romaji: "su" },
  { id: "se", script: "hiragana", char: "せ", romaji: "se" },
  { id: "so", script: "hiragana", char: "そ", romaji: "so" },
  { id: "za", script: "hiragana", char: "ざ", romaji: "za" },
  { id: "ji", script: "hiragana", char: "じ", romaji: "ji" },
  { id: "zu", script: "hiragana", char: "ず", romaji: "zu" },
  { id: "ze", script: "hiragana", char: "ぜ", romaji: "ze" },
  { id: "zo", script: "hiragana", char: "ぞ", romaji: "zo" },
  { id: "ta", script: "hiragana", char: "た", romaji: "ta" },
  { id: "chi", script: "hiragana", char: "ち", romaji: "chi", confusion: ["shi"] },
  { id: "tsu", script: "hiragana", char: "つ", romaji: "tsu", confusion: ["shi"] },
  { id: "te", script: "hiragana", char: "て", romaji: "te" },
  { id: "to", script: "hiragana", char: "と", romaji: "to" },
  { id: "da", script: "hiragana", char: "だ", romaji: "da" },
  { id: "di", script: "hiragana", char: "ぢ", romaji: "di" },
  { id: "du", script: "hiragana", char: "づ", romaji: "du" },
  { id: "de", script: "hiragana", char: "で", romaji: "de" },
  { id: "do", script: "hiragana", char: "ど", romaji: "do" },
  { id: "na", script: "hiragana", char: "な", romaji: "na" },
  { id: "ni", script: "hiragana", char: "に", romaji: "ni" },
  { id: "nu", script: "hiragana", char: "ぬ", romaji: "nu", confusion: ["ne", "me"] },
  { id: "ne", script: "hiragana", char: "ね", romaji: "ne", confusion: ["nu", "me"] },
  { id: "no", script: "hiragana", char: "の", romaji: "no" },
  { id: "ha", script: "hiragana", char: "は", romaji: "ha" },
  { id: "hi", script: "hiragana", char: "ひ", romaji: "hi" },
  { id: "fu", script: "hiragana", char: "ふ", romaji: "fu" },
  { id: "he", script: "hiragana", char: "へ", romaji: "he" },
  { id: "ho", script: "hiragana", char: "ほ", romaji: "ho" },
  { id: "ba", script: "hiragana", char: "ば", romaji: "ba" },
  { id: "bi", script: "hiragana", char: "び", romaji: "bi" },
  { id: "bu", script: "hiragana", char: "ぶ", romaji: "bu" },
  { id: "be", script: "hiragana", char: "べ", romaji: "be" },
  { id: "bo", script: "hiragana", char: "ぼ", romaji: "bo" },
  { id: "pa", script: "hiragana", char: "ぱ", romaji: "pa" },
  { id: "pi", script: "hiragana", char: "ぴ", romaji: "pi" },
  { id: "pu", script: "hiragana", char: "ぷ", romaji: "pu" },
  { id: "pe", script: "hiragana", char: "ぺ", romaji: "pe" },
  { id: "po", script: "hiragana", char: "ぽ", romaji: "po" },
  { id: "ma", script: "hiragana", char: "ま", romaji: "ma" },
  { id: "mi", script: "hiragana", char: "み", romaji: "mi" },
  { id: "mu", script: "hiragana", char: "む", romaji: "mu" },
  { id: "me", script: "hiragana", char: "め", romaji: "me", confusion: ["ne", "nu"] },
  { id: "mo", script: "hiragana", char: "も", romaji: "mo" },
  { id: "ya", script: "hiragana", char: "や", romaji: "ya" },
  { id: "yu", script: "hiragana", char: "ゆ", romaji: "yu" },
  { id: "yo", script: "hiragana", char: "よ", romaji: "yo" },
  { id: "ra", script: "hiragana", char: "ら", romaji: "ra" },
  { id: "ri", script: "hiragana", char: "り", romaji: "ri" },
  { id: "ru", script: "hiragana", char: "る", romaji: "ru" },
  { id: "re", script: "hiragana", char: "れ", romaji: "re" },
  { id: "ro", script: "hiragana", char: "ろ", romaji: "ro" },
  { id: "wa", script: "hiragana", char: "わ", romaji: "wa" },
  { id: "wi", script: "hiragana", char: "ゐ", romaji: "wi" },
  { id: "we", script: "hiragana", char: "ゑ", romaji: "we" },
  { id: "wo", script: "hiragana", char: "を", romaji: "wo" },
  { id: "n", script: "hiragana", char: "ん", romaji: "n" },
];

export const katakana: KanaEntry[] = [
  { id: "a-k", script: "katakana", char: "ア", romaji: "a" },
  { id: "i-k", script: "katakana", char: "イ", romaji: "i" },
  { id: "u-k", script: "katakana", char: "ウ", romaji: "u" },
  { id: "e-k", script: "katakana", char: "エ", romaji: "e" },
  { id: "o-k", script: "katakana", char: "オ", romaji: "o" },
  { id: "ka-k", script: "katakana", char: "カ", romaji: "ka" },
  { id: "ki-k", script: "katakana", char: "キ", romaji: "ki" },
  { id: "ku-k", script: "katakana", char: "ク", romaji: "ku" },
  { id: "ke-k", script: "katakana", char: "ケ", romaji: "ke" },
  { id: "ko-k", script: "katakana", char: "コ", romaji: "ko" },
  { id: "ga-k", script: "katakana", char: "ガ", romaji: "ga" },
  { id: "gi-k", script: "katakana", char: "ギ", romaji: "gi" },
  { id: "gu-k", script: "katakana", char: "グ", romaji: "gu" },
  { id: "ge-k", script: "katakana", char: "ゲ", romaji: "ge" },
  { id: "go-k", script: "katakana", char: "ゴ", romaji: "go" },
  { id: "sa-k", script: "katakana", char: "サ", romaji: "sa" },
  { id: "shi-k", script: "katakana", char: "シ", romaji: "shi", confusion: ["tsu-k"] },
  { id: "su-k", script: "katakana", char: "ス", romaji: "su" },
  { id: "se-k", script: "katakana", char: "セ", romaji: "se" },
  { id: "so-k", script: "katakana", char: "ソ", romaji: "so", confusion: ["n-k"] },
  { id: "za-k", script: "katakana", char: "ザ", romaji: "za" },
  { id: "ji-k", script: "katakana", char: "ジ", romaji: "ji" },
  { id: "zu-k", script: "katakana", char: "ズ", romaji: "zu" },
  { id: "ze-k", script: "katakana", char: "ゼ", romaji: "ze" },
  { id: "zo-k", script: "katakana", char: "ゾ", romaji: "zo" },
  { id: "ta-k", script: "katakana", char: "タ", romaji: "ta" },
  { id: "chi-k", script: "katakana", char: "チ", romaji: "chi", confusion: ["shi-k"] },
  { id: "tsu-k", script: "katakana", char: "ツ", romaji: "tsu", confusion: ["shi-k"] },
  { id: "te-k", script: "katakana", char: "テ", romaji: "te" },
  { id: "to-k", script: "katakana", char: "ト", romaji: "to" },
  { id: "da-k", script: "katakana", char: "ダ", romaji: "da" },
  { id: "di-k", script: "katakana", char: "ヂ", romaji: "di" },
  { id: "du-k", script: "katakana", char: "ヅ", romaji: "du" },
  { id: "de-k", script: "katakana", char: "デ", romaji: "de" },
  { id: "do-k", script: "katakana", char: "ド", romaji: "do" },
  { id: "na-k", script: "katakana", char: "ナ", romaji: "na" },
  { id: "ni-k", script: "katakana", char: "ニ", romaji: "ni" },
  { id: "nu-k", script: "katakana", char: "ヌ", romaji: "nu", confusion: ["ne-k", "me-k"] },
  { id: "ne-k", script: "katakana", char: "ネ", romaji: "ne", confusion: ["nu-k", "me-k"] },
  { id: "no-k", script: "katakana", char: "ノ", romaji: "no" },
  { id: "ha-k", script: "katakana", char: "ハ", romaji: "ha" },
  { id: "hi-k", script: "katakana", char: "ヒ", romaji: "hi" },
  { id: "fu-k", script: "katakana", char: "フ", romaji: "fu" },
  { id: "he-k", script: "katakana", char: "ヘ", romaji: "he" },
  { id: "ho-k", script: "katakana", char: "ホ", romaji: "ho" },
  { id: "ba-k", script: "katakana", char: "バ", romaji: "ba" },
  { id: "bi-k", script: "katakana", char: "ビ", romaji: "bi" },
  { id: "bu-k", script: "katakana", char: "ブ", romaji: "bu" },
  { id: "be-k", script: "katakana", char: "ベ", romaji: "be" },
  { id: "bo-k", script: "katakana", char: "ボ", romaji: "bo" },
  { id: "pa-k", script: "katakana", char: "パ", romaji: "pa" },
  { id: "pi-k", script: "katakana", char: "ピ", romaji: "pi" },
  { id: "pu-k", script: "katakana", char: "プ", romaji: "pu" },
  { id: "pe-k", script: "katakana", char: "ペ", romaji: "pe" },
  { id: "po-k", script: "katakana", char: "ポ", romaji: "po" },
  { id: "ma-k", script: "katakana", char: "マ", romaji: "ma" },
  { id: "mi-k", script: "katakana", char: "ミ", romaji: "mi" },
  { id: "mu-k", script: "katakana", char: "ム", romaji: "mu" },
  { id: "me-k", script: "katakana", char: "メ", romaji: "me", confusion: ["ne-k", "nu-k"] },
  { id: "mo-k", script: "katakana", char: "モ", romaji: "mo" },
  { id: "ya-k", script: "katakana", char: "ヤ", romaji: "ya" },
  { id: "yu-k", script: "katakana", char: "ユ", romaji: "yu" },
  { id: "yo-k", script: "katakana", char: "ヨ", romaji: "yo" },
  { id: "ra-k", script: "katakana", char: "ラ", romaji: "ra" },
  { id: "ri-k", script: "katakana", char: "リ", romaji: "ri" },
  { id: "ru-k", script: "katakana", char: "ル", romaji: "ru" },
  { id: "re-k", script: "katakana", char: "レ", romaji: "re" },
  { id: "ro-k", script: "katakana", char: "ロ", romaji: "ro" },
  { id: "wa-k", script: "katakana", char: "ワ", romaji: "wa" },
  { id: "wi-k", script: "katakana", char: "ヰ", romaji: "wi" },
  { id: "we-k", script: "katakana", char: "ヱ", romaji: "we" },
  { id: "wo-k", script: "katakana", char: "ヲ", romaji: "wo" },
  { id: "n-k", script: "katakana", char: "ン", romaji: "n", confusion: ["so-k"] },
];
