export type KanjiEntry = {
  id: string;
  kanji: string;
  reading: string; // hiragana
  meaning: string;
  level: number;
};

export const n5Kanji: KanjiEntry[] = [
  { id: "hito", kanji: "人", reading: "ひと", meaning: "person", level: 1 },
  { id: "ki", kanji: "木", reading: "き", meaning: "tree", level: 1 },
  { id: "kuchi", kanji: "口", reading: "くち", meaning: "mouth", level: 1 },
  { id: "te", kanji: "手", reading: "て", meaning: "hand", level: 1 },
  { id: "me", kanji: "目", reading: "め", meaning: "eye", level: 1 },
  { id: "hi", kanji: "日", reading: "ひ", meaning: "sun/day", level: 1 },
  { id: "tsuki", kanji: "月", reading: "つき", meaning: "moon/month", level: 1 },
  { id: "yama", kanji: "山", reading: "やま", meaning: "mountain", level: 1 },
  { id: "kawa", kanji: "川", reading: "かわ", meaning: "river", level: 1 },
  { id: "umi", kanji: "海", reading: "うみ", meaning: "sea", level: 1 },
  { id: "hoshi", kanji: "星", reading: "ほし", meaning: "star", level: 2 },
  { id: "kumo", kanji: "雲", reading: "くも", meaning: "cloud", level: 2 },
  { id: "yuki", kanji: "雪", reading: "ゆき", meaning: "snow", level: 2 },
  { id: "ame", kanji: "雨", reading: "あめ", meaning: "rain", level: 2 },
  { id: "kaze", kanji: "風", reading: "かぜ", meaning: "wind", level: 2 },
  { id: "mizu", kanji: "水", reading: "みず", meaning: "water", level: 2 },
  { id: "hi-fire", kanji: "火", reading: "ひ", meaning: "fire", level: 2 },
  { id: "kane", kanji: "金", reading: "かね", meaning: "gold/money", level: 2 },
  { id: "tsuchi", kanji: "土", reading: "つち", meaning: "earth", level: 2 },
  { id: "ishi", kanji: "石", reading: "いし", meaning: "stone", level: 2 },
  { id: "onna", kanji: "女", reading: "おんな", meaning: "woman", level: 3 },
  { id: "otoko", kanji: "男", reading: "おとこ", meaning: "man", level: 3 },
  { id: "ko", kanji: "子", reading: "こ", meaning: "child", level: 3 },
  { id: "chisai", kanji: "小", reading: "ちいさい", meaning: "small", level: 3 },
  { id: "ookii", kanji: "大", reading: "おおきい", meaning: "big", level: 3 },
  { id: "akai", kanji: "赤", reading: "あかい", meaning: "red", level: 3 },
  { id: "aoi", kanji: "青", reading: "あおい", meaning: "blue", level: 3 },
  { id: "shiroi", kanji: "白", reading: "しろい", meaning: "white", level: 3 },
  { id: "kuroi", kanji: "黒", reading: "くろい", meaning: "black", level: 3 },
  { id: "gakkou", kanji: "学", reading: "がく", meaning: "study", level: 3 },
  { id: "sei", kanji: "生", reading: "せい", meaning: "life", level: 3 },
  { id: "sen", kanji: "先", reading: "せん", meaning: "previous", level: 3 },
  { id: "koo", kanji: "校", reading: "こう", meaning: "school", level: 3 },
  { id: "joo", kanji: "上", reading: "じょう", meaning: "up", level: 3 },
  { id: "shita", kanji: "下", reading: "した", meaning: "down", level: 3 },
  { id: "migi", kanji: "右", reading: "みぎ", meaning: "right", level: 3 },
  { id: "hidari", kanji: "左", reading: "ひだり", meaning: "left", level: 3 },
  { id: "naka", kanji: "中", reading: "なか", meaning: "middle", level: 3 },
  { id: "mae", kanji: "前", reading: "まえ", meaning: "front", level: 3 },
  { id: "ushiro", kanji: "後", reading: "うしろ", meaning: "behind", level: 3 },
  { id: "densha", kanji: "電", reading: "でん", meaning: "electricity", level: 4 },
  { id: "kuruma", kanji: "車", reading: "くるま", meaning: "car", level: 4 },
  { id: "eki", kanji: "駅", reading: "えき", meaning: "station", level: 4 },
  { id: "ie", kanji: "家", reading: "いえ", meaning: "house", level: 4 },
  { id: "doa", kanji: "戸", reading: "と", meaning: "door", level: 4 },
  { id: "mado", kanji: "窓", reading: "まど", meaning: "window", level: 4 },
  { id: "yuka", kanji: "床", reading: "ゆか", meaning: "floor", level: 4 },
  { id: "teburu", kanji: "机", reading: "つくえ", meaning: "desk", level: 4 },
  { id: "kisu", kanji: "椅", reading: "いす", meaning: "chair", level: 4 },
  { id: "kukkingu", kanji: "食", reading: "しょく", meaning: "food", level: 4 },
  { id: "shokutaku", kanji: "飯", reading: "めし", meaning: "meal", level: 4 },
  { id: "pan", kanji: "麺", reading: "めん", meaning: "noodles", level: 4 },
  { id: "sakana", kanji: "魚", reading: "さかな", meaning: "fish", level: 4 },
  { id: "niku", kanji: "肉", reading: "にく", meaning: "meat", level: 4 },
  { id: "pan-bread", kanji: "肺", reading: "はい", meaning: "lung", level: 4 },
  { id: "gyuunyuu", kanji: "牛", reading: "ぎゅう", meaning: "cow", level: 4 },
  { id: "niwatori", kanji: "鶏", reading: "にわとり", meaning: "chicken", level: 4 },
  { id: "inu", kanji: "犬", reading: "いぬ", meaning: "dog", level: 5 },
  { id: "neko", kanji: "猫", reading: "ねこ", meaning: "cat", level: 5 },
  { id: "tori", kanji: "鳥", reading: "とり", meaning: "bird", level: 5 },
  { id: "sora", kanji: "空", reading: "そら", meaning: "sky", level: 5 },
  { id: "tsuyoi", kanji: "強", reading: "つよい", meaning: "strong", level: 5 },
  { id: "yowai", kanji: "弱", reading: "よわい", meaning: "weak", level: 5 },
  { id: "atatakai", kanji: "温", reading: "あたたかい", meaning: "warm", level: 5 },
  { id: "tsumetai", kanji: "冷", reading: "つめたい", meaning: "cold", level: 5 },
  { id: "atsu", kanji: "暑", reading: "あつい", meaning: "hot (weather)", level: 5 },
  { id: "samui", kanji: "寒", reading: "さむい", meaning: "cold (weather)", level: 5 },
];
