export type VocabEntry = {
  id: string;
  term: string; // kanji/kana form
  reading: string; // hiragana
  meaning: string;
  level: number;
};

export const n5Vocab: VocabEntry[] = [
  { id: "konnichiwa", term: "こんにちは", reading: "こんにちは", meaning: "hello", level: 1 },
  { id: "arigatou", term: "ありがとう", reading: "ありがとう", meaning: "thank you", level: 1 },
  { id: "ohayou", term: "おはよう", reading: "おはよう", meaning: "good morning", level: 1 },
  { id: "konbanwa", term: "こんばんは", reading: "こんばんは", meaning: "good evening", level: 1 },
  { id: "sayounara", term: "さようなら", reading: "さようなら", meaning: "goodbye", level: 1 },
  { id: "sumimasen", term: "すみません", reading: "すみません", meaning: "excuse me", level: 1 },
  { id: "gomen", term: "ごめん", reading: "ごめん", meaning: "sorry", level: 1 },
  { id: "hai", term: "はい", reading: "はい", meaning: "yes", level: 1 },
  { id: "iie", term: "いいえ", reading: "いいえ", meaning: "no", level: 1 },
  { id: "wakarimashita", term: "わかりました", reading: "わかりました", meaning: "I understand", level: 1 },
  { id: "ie", term: "家", reading: "いえ", meaning: "house", level: 2 },
  { id: "gakkou", term: "学校", reading: "がっこう", meaning: "school", level: 2 },
  { id: "kuruma", term: "車", reading: "くるま", meaning: "car", level: 2 },
  { id: "eki", term: "駅", reading: "えき", meaning: "station", level: 2 },
  { id: "densha", term: "電車", reading: "でんしゃ", meaning: "train", level: 2 },
  { id: "hoteru", term: "ホテル", reading: "ほてる", meaning: "hotel", level: 2 },
  { id: "toshokan", term: "図書館", reading: "としょかん", meaning: "library", level: 2 },
  { id: "byouin", term: "病院", reading: "びょういん", meaning: "hospital", level: 2 },
  { id: "resutoran", term: "レストラン", reading: "れすとらん", meaning: "restaurant", level: 2 },
  { id: "depato", term: "デパート", reading: "でぱーと", meaning: "department store", level: 2 },
  { id: "mizu", term: "水", reading: "みず", meaning: "water", level: 3 },
  { id: "ocha", term: "お茶", reading: "おちゃ", meaning: "tea", level: 3 },
  { id: "koohii", term: "コーヒー", reading: "こーひー", meaning: "coffee", level: 3 },
  { id: "gohan", term: "ご飯", reading: "ごはん", meaning: "meal/rice", level: 3 },
  { id: "pan", term: "パン", reading: "ぱん", meaning: "bread", level: 3 },
  { id: "yasai", term: "野菜", reading: "やさい", meaning: "vegetable", level: 3 },
  { id: "sakana", term: "魚", reading: "さかな", meaning: "fish", level: 3 },
  { id: "niku", term: "肉", reading: "にく", meaning: "meat", level: 3 },
  { id: "tamago", term: "卵", reading: "たまご", meaning: "egg", level: 3 },
  { id: "kase", term: "チーズ", reading: "ちーず", meaning: "cheese", level: 3 },
  { id: "inu", term: "犬", reading: "いぬ", meaning: "dog", level: 4 },
  { id: "neko", term: "猫", reading: "ねこ", meaning: "cat", level: 4 },
  { id: "tori", term: "鳥", reading: "とり", meaning: "bird", level: 4 },
  { id: "sora", term: "空", reading: "そら", meaning: "sky", level: 4 },
  { id: "ame", term: "雨", reading: "あめ", meaning: "rain", level: 4 },
  { id: "yuki", term: "雪", reading: "ゆき", meaning: "snow", level: 4 },
  { id: "kaze", term: "風", reading: "かぜ", meaning: "wind", level: 4 },
  { id: "kumo", term: "雲", reading: "くも", meaning: "cloud", level: 4 },
  { id: "hana", term: "花", reading: "はな", meaning: "flower", level: 4 },
  { id: "ki-tree", term: "木", reading: "き", meaning: "tree", level: 4 },
  { id: "heya", term: "部屋", reading: "へや", meaning: "room", level: 5 },
  { id: "beddo", term: "ベッド", reading: "べっど", meaning: "bed", level: 5 },
  { id: "sofa", term: "ソファ", reading: "そふぁ", meaning: "sofa", level: 5 },
  { id: "teburu", term: "テーブル", reading: "てーぶる", meaning: "table", level: 5 },
  { id: "isu", term: "椅子", reading: "いす", meaning: "chair", level: 5 },
  { id: "doa", term: "ドア", reading: "どあ", meaning: "door", level: 5 },
  { id: "mado", term: "窓", reading: "まど", meaning: "window", level: 5 },
  { id: "kabin", term: "内装", reading: "ないそう", meaning: "interior", level: 5 },
  { id: "denki", term: "電気", reading: "でんき", meaning: "electricity", level: 5 },
  { id: "roji", term: "廊下", reading: "ろうか", meaning: "hallway", level: 5 },
];
